/*
EXERCISE TITLE:
Introductory Asynchronous Testing

EXERCISE TEXT:
One important aspect of web applications is the ability to respond to asynchronous events.

Examples of asynchronous events are network operations, like the response received from a server carrying new data. Events generated by the user interacting with the UI, and in general any operation which is triggered at some point in time which we cannot predict.

The functional nature of JavaScript makes the language particularly suited to handle asynchronous operations. In fact JavaScript allows a mixture of different constructs that can be used reliably to handle asynchronous events.

As we will see in this exercise, logic that responds to asynchronous calls has specific requirements with regards to testing.

We use _asynchronous testing_ because we have to wait somehow for the necessary parts involved to be in a correct state. For example, when the data we need comlete loading.

### Mocking Data
Because we are testing our functionality on data which may change in the future and grow in the order of thousands of records, we may not be able to run our tests using all possible data that may come in.

In this case we use a technique called __mocking__, in which we create some specific mocked data like it would be the real ones. Then we use the mocked data in the tests and pass it to our logic in order to see if the results produced match what we expect.

QUnit offers some features out of the box to support asynchronous testing, which are very intuitive and easy to use.

 */

/*
EXERCISE TEST

The exercise will use the JSON data we encountered before representing some soccer players statistics.

The top management wants to know some information about the players contained in the data.
After loading the data set, some logic will use those data to extract the information requested by the management.

Extracting this information is not difficult, but we need to make sure the results are accurate, given the target audience that is asking for it. A good job to test driving our logic!

Only a part of the data the management asked for is being extracted. But most of all, the logic currently written is wrong... It is extracting wrong resuts!

You are required to fix that by correcting (or completely rewriting) the wrong logic for the data features currently extracted.

Then, you should add more tests (as much as you deem necessary) that cover the extraction of the other data features the management has requested and make sure that also those results will be correct using the logic you fixed.



This is the last effort of this Session 1, and should finally consolidate in you the help that testing can bring to the table.

Good luck!

As usual, if you are stuck, see additional hints below.
 */

/*
EXERCISE HINTS

The function findMax() which finds the elements with max value for a given data feature (or property) is wrong. When two elements have the same values that is not being counted accurately, plus it has some more problems too.

Rewrite that logic. The function should iltimately return an array of ids of those players which satisfy the feature requested. For example, if we are looking for the players with the most goals, we should get back an array with elements [1, 19], not necessarily in order.

*/
/*
    
    - Find the player with the higest score
    - Find the player with the most yellow cards
    - Find the player with the most red cards

 */

var _ = require("underscore");

(function exercise5(){
    
    var dataLoader = function(){
        return {
            load: function loadFn(url){
                return $.getJSON(url);
            }
        };
    },

    loadPlayerData = function loadPlayerData(url){
            //return $.getJSON(url);
            return {
                done: function mockDone(fn){
                    fn.call(null, {
                        "season": 2013,
                        "players": [{
                            "id": 1,
                            "playerName": "Carlos Tévez",
                            "teamName": "Juventus",
                            "position": "Attacking Midfielder (Center, Left) / Forward",
                            "appearances": 28,
                            "goals": 19,
                            "yellowCards": 4,
                            "redCards": 0,
                            "totalShots": 120
                        },
                        {
                            "id": 2,
                            "playerName": "Juan Guillermo Cu...",
                            "teamName": "Fiorentina",
                            "position": "Defender (Right) / Midfielder (Center, Left, Right)",
                            "appearances": 28,
                            "goals": 9,
                            "yellowCards": 6,
                            "redCards": 1,
                            "totalShots": 84
                        },
                        {
                            "id": 3,
                            "playerName": "Paul Pogba",
                            "teamName": "Juventus",
                            "position": "Defensive Midfielder (Center)",
                            "appearances": 30,
                            "goals": 7,
                            "yellowCards": 4,
                            "redCards": 0,
                            "totalShots": 66
                        },
                        {
                            "id": 4,
                            "playerName": "Giorgio Chiellini",
                            "teamName": "Juventus",
                            "position": "Defender (Center, Left)",
                            "appearances": 29,
                            "goals": 3,
                            "yellowCards": 4,
                            "redCards": 0,
                            "totalShots": 24
                        },
                        {
                            "id": 5,
                            "playerName": "Mehdi Benatia",
                            "teamName": "Roma",
                            "position": "Defender (Center)",
                            "appearances": 30,
                            "goals": 5,
                            "yellowCards": 8,
                            "redCards": 0,
                            "totalShots": 18
                        },
                        {
                            "id": 6,
                            "playerName": "Andrea Pirlo",
                            "teamName": "Juventus",
                            "position": "Midfielder (Center)",
                            "appearances": 27,
                            "goals": 4,
                            "yellowCards": 4,
                            "redCards": 0,
                            "totalShots": 46
                        },
                        {
                            "id": 7,
                            "playerName": "Alessandro Lucarelli",
                            "teamName": "Parma",
                            "position": "Defender (Center, Left)",
                            "appearances": 32,
                            "goals": 4,
                            "yellowCards": 14,
                            "redCards": 0,
                            "totalShots": 17
                        },
                        {
                            "id": 8,
                            "playerName": "Miralem Pjanic",
                            "teamName": "Roma",
                            "position": "Midfielder (Center, Right)",
                            "appearances": 30,
                            "goals": 6,
                            "yellowCards": 5,
                            "redCards": 1,
                            "totalShots": 68
                        },
                        {
                            "id": 9,
                            "playerName": "Daniele De Rossi",
                            "teamName": "Roma",
                            "position": "Defender (Center) / Defensive Midfielder (Center)",
                            "appearances": 29,
                            "goals": 1,
                            "yellowCards": 4,
                            "redCards": 1,
                            "totalShots": 31
                        },
                        {
                            "id": 10,
                            "playerName": "Giuseppe Rossi",
                            "teamName": "Fiorentina",
                            "position": "Attacking Midfielder (Left) / Forward",
                            "appearances": 18,
                            "goals": 14,
                            "yellowCards": 1,
                            "redCards": 0,
                            "totalShots": 60
                        },
                        {
                            "id": 11,
                            "playerName": "Arturo Vidal",
                            "teamName": "Juventus",
                            "position": "Midfielder (Center)",
                            "appearances": 28,
                            "goals": 11,
                            "yellowCards": 8,
                            "redCards": 0,
                            "totalShots": 57
                        },
                        {
                            "id": 12,
                            "playerName": "Hugo Campagnaro",
                            "teamName": "Inter",
                            "position": "Defender (Center)",
                            "appearances": 19,
                            "goals": 0,
                            "yellowCards": 4,
                            "redCards": 0,
                            "totalShots": 3
                        },
                        {
                            "id": 13,
                            "playerName": "Ricardo Álvarez",
                            "teamName": "Inter",
                            "position": "Attacking Midfielder (Center, Left, Right)",
                            "appearances": 24,
                            "goals": 4,
                            "yellowCards": 3,
                            "redCards": 1,
                            "totalShots": 47
                        },
                        {
                            "id": 14,
                            "playerName": "Rodrigo Palacio",
                            "teamName": "Inter",
                            "position": "Attacking Midfielder (Center, Left, Right) / Forward",
                            "appearances": 34,
                            "goals": 15,
                            "yellowCards": 3,
                            "redCards": 0,
                            "totalShots": 88
                        },
                        {
                            "id": 15,
                            "playerName": "Gervinho",
                            "teamName": "Roma",
                            "position": "Attacking Midfielder (Left, Right) / Forward",
                            "appearances": 29,
                            "goals": 9,
                            "yellowCards": 1,
                            "redCards": 0,
                            "totalShots": 61
                        },
                        {
                            "id": 16,
                            "playerName": "Alessandro Diamanti",
                            "teamName": "Bologna",
                            "position": "Attacking Midfielder (Center, Left, Right) / Forward",
                            "appearances": 19,
                            "goals": 5,
                            "yellowCards": 9,
                            "redCards": 0,
                            "totalShots": 82
                        },
                        {
                            "id": 17,
                            "playerName": "Francesco Totti",
                            "teamName": "Roma",
                            "position": "Attacking Midfielder (Center, Left) / Forward",
                            "appearances": 18,
                            "goals": 7,
                            "yellowCards": 1,
                            "redCards": 0,
                            "totalShots": 61
                        },
                        {
                            "id": 18,
                            "playerName": "Kevin Strootman",
                            "teamName": "Roma",
                            "position": "Defensive Midfielder (Center)",
                            "appearances": 24,
                            "goals": 5,
                            "yellowCards": 6,
                            "redCards": 0,
                            "totalShots": 36
                        },
                        {
                            "id": 19,
                            "playerName": "Luca Toni",
                            "teamName": "Verona",
                            "position": "Forward",
                            "appearances": 31,
                            "goals": 19,
                            "yellowCards": 4,
                            "redCards": 0,
                            "totalShots": 111
                        },
                        {
                            "id": 20,
                            "playerName": "Gonzalo Rodríguez",
                            "teamName": "Fiorentina",
                            "position": "Defender (Center, Left)",
                            "appearances": 30,
                            "goals": 3,
                            "yellowCards": 12,
                            "redCards": 0,
                            "totalShots": 16
                        }]
                    });
                },
                fail: function mockFail(){}
            };
        },

        // Reusable function that can find the highest property value in a list
        // of objects
        /*maxFinder = function maxFinder(list){
            return function findMax(prop){
                var maxVal = 0,
                    maxes = _.filter(list, function mapFn(item){
                        if (item[prop] >= maxVal){
                            maxVal = item[prop];
                        }
                        return item[prop] >= maxVal;
                    });
                return maxes;
                /*return _.max(list, function forEachItem(item){
                    return item[prop];
                });*
            };
        };*/

        maxFinder = function maxFinder(list){
            return function findMax(prop){
                var max = 0,
                    maxes = _.filter(list, function filterFn(item){
                        if (item[prop] >= max){
                            max = item[prop];
                            return item;
                        }
                    });
                maxes = _.filter(maxes, function filterMaxesFn(item){
                    return item[prop] === max;
                });

                return maxes;
            };
        };

    (function tests(){
        
        var

            dataLoadPromise = loadPlayerData("./players.js"),
            findMax,
            maxGoalPlayes,
            maxYellowCardPlayers,
            mostPlayedPlayers,
            maxRedCardPlayers;

        dataLoadPromise.done(function dataLoadDone(data){
            findMax = maxFinder(data.players);

            maxGoalPlayes = findMax("goals");
            maxYellowCardPlayers = findMax("yellowCards");
            maxRedCardPlayers = findMax("redCards");
            mostPlayedPlayers = findMax("appearances");

            var expectedMaxGoalIds = [19, 1];
            // First we check that the array should be of the correct length
            console.log("array should be of the correct length:",
                        maxGoalPlayes.length === expectedMaxGoalIds.length,
                        maxGoalPlayes.length);

            console.log("The expected player ids should match:",
                maxGoalPlayes.every(function everyFn(item){
                    return expectedMaxGoalIds.indexOf(item.id) >= 0;
                }),
                expectedMaxGoalIds
            );

            var expectedYellowCardIds = [7];
            console.log("array should be of the correct length:",
                        expectedYellowCardIds.length === 1,
                        expectedYellowCardIds.length);

            console.log("The expected player ids should match:",
                maxYellowCardPlayers.every(function everyFn(item){
                    return expectedYellowCardIds.indexOf(item.id) >= 0;
                }),
                expectedYellowCardIds
            );

            var expectedMostPlayedIds = [14];
            console.log("array should be of the correct length:",
                        mostPlayedPlayers.length === 1,
                        mostPlayedPlayers.length);

            console.log("The expected player ids should match:",
                    mostPlayedPlayers[0].id === 14,
                    expectedMostPlayedIds
            );
        });

        dataLoadPromise.fail(function dataLoadFail(jqXHR, textStatus){
            console.log(textStatus);
        });

    }());
}());